name: Make/Check bare bone

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, macos-latest, macos-10.15 ]
        arch: [ adm64, i386, arm, arm64, ppc64el ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: echo runner OS
      run: echo "The OS is $RUNNER_OS"
    - name: install Linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install check
    - name: install macOS dependencies
      if: runner.os == 'macOS'
      run: brew install automake check
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check

