name: Make and Check without 3rd party libs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04 ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: check runner OS
      if: ${{ env.RUNNER_OS == "Linux" }}
      run: echo "Yeaha this is LINUX"
    - name: install dependencies
      run: sudo apt-get install check
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check

